apiVersion: v1
kind: ConfigMap
metadata:
  name: hacka-msc-pcs-midia-config
data:
  ENV: ""
  AWS_REGION: ""
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_SESSION_TOKEN: ""
  HACKA_BUCKET_NAME_MEDIA_FILES: ""
  QUEUE_NAME_PROCESSING: ""
  QUEUE_NAME_RESULT: ""