apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacka-msc-pcs-midia
  labels:
    app: hacka-msc-pcs-midia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacka-msc-pcs-midia
  template:
    metadata:
      labels:
        app: hacka-msc-pcs-midia
    spec:
      containers:
        - name: hacka-msc-pcs-midia
          image: josevitordurante/hacka-msc-pcs-midia:latest
          ports:
            - containerPort: 8089
          env:
            - name: PORT
              value: "8089"
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: ENV
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: AWS_SECRET_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: AWS_SESSION_TOKEN
            - name: QUEUE_NAME_PROCESSING
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: QUEUE_NAME_PROCESSING
            - name: QUEUE_NAME_RESULT
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: QUEUE_NAME_RESULT
            - name: HACKA_BUCKET_NAME_MEDIA_FILES
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-pcs-midia-config
                  key: HACKA_BUCKET_NAME_MEDIA_FILES
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
