apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-and-configmap-access-binding-hacka-msc-pcs-midia
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: service-and-configmap-access
  apiGroup: rbac.authorization.k8s.io
